#!/usr/bin/env bash
# install nginx
apt-get update  
apt-get install -y nginx;
apt-get update

# change content of default_server
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# star service nginx
service nginx start;
