#!/usr/bin/env bash
# install nginx
apt-get update  
apt-get install -y nginx;

# change content of default_server
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html

# variable entorno
redirect="\\\n\t# Redirection\n\trewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "/server_name _;/ a $redirect" /etc/nginx/sites-available/default

# star service nginx
service nginx restart;
