#!/usr/bin/env bash
# install nginx else exist
if ! [ -x "$(command -v nginx)" ]
then
	apt-get update -y;
	apt-get upgrade -y;
	apt-get install -y nginx;
fi

# change content of default_server
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# variable entorno
command="\\\n\t# Redirection\n\trewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "/server_name _;/a$command" /etc/nginx/sites-available/default

# star service nginx
service nginx restart;
